import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthContextProvider from "@/modules/auth_provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthContextProvider>
        <body
          className={
            inter.className + "flex  flex-col md:flex-row h-full min-h-screen"
          }
        >
          {children}
        </body>
      </AuthContextProvider>
    </html>
  );
}
